### PR TITLE
Don't warn if a computed property doesn't have a type.

### LINKED ISSUE #65: computed property without reflect type error
Hi,

This line produce an error that can't be worked arround without `Reflect` using `computed` properties:

https://github.com/Polymer/polymer-decorators/blob/0842e694c1995a0a59fed78f2ae3115fc7a26e2b/src/decorators.ts#L99

Cheers

### PR DESCRIPTION
**Pull request by aomarks**
The type is only used for attribute de-serialization, which never  happens with computed properties because they are read-only, so this warning is useless.

Fixes #65

### CODE REVIEW

**Comment by justinfagnani** [comment]
I think we should also not warn if the property doesn't reflect.

**Comment by aomarks** [comment]
> I think we should also not warn if the property doesn't reflect.

`reflectToAttribute: false` means setting the property won't update the attribute, but we always update the property when a binding on an attribute updates, and hence need a de-serialization function, right?

**Comment by justinfagnani** [comment]
Oh right, but it's actually slightly different. The `type` field controls the deserialization. If it's one of a few known values, it'll be deserialized. cc @kevinpschaaf and @sorvell

**Comment by aomarks** [comment]
> Oh right, but it's actually slightly different. The type field controls the deserialization. If it's one of a few known values, it'll be deserialized. cc @kevinpschaaf and @sorvell

Right. What's the issue though?

**Comment by justinfagnani** [comment]
> Right. What's the issue though?

It's not clear that leaving out type should be a warning at all? It would either just disable serialization, or default to... String?

**Comment by aomarks** [comment]
> It's not clear that leaving out type should be a warning at all? It would either just disable serialization, or default to... String?

String, yes.

**Comment by aomarks** [comment]
> It's not clear that leaving out type should be a warning at all? It would either just disable serialization, or default to... String?
> 
> String, yes.

The reason I added the warning originally was out of concern that people might be assuming that metadata reflection was working even if it wasn't set up right, which could cause hard to debug errors later, since you'd just be getting the wrong type in certain cases.

**Pull request merged**
